Candy/Pages/Accesso.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Candy.Pages
{
    public class AccessoModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Candy/Pages/Amministrazione.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace Candy.Pages
{
    public class AmministrazioneModel : PageModel
    {
        public string nome;
        public void OnGet()
        {
        }
        public void OnPost(string nome)
        {
            this.nome = nome;
        }
    }
}

Candy/Pages/Carrello.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Candy.Pages
{
    public class CarrelloModel : PageModel
    {
        public Prodotto prod = new Prodotto();
        public string action;
        public void OnGet()
        {
        }
        public void OnPost(int quantProd, string nomeProd, double prezProd, string btn)
        {
            this.prod.quantita = quantProd;
            this.prod.nome = nomeProd;
            this.prod.prezzo = prezProd;
            this.action = btn;
        }
        public int FindProd(string nome, List<Prodotto> products) // trova un determinato prodotto
        {
            for (int i = 0; i < products.Count; i++)
            {
                if (nome == products[i].nome)
                    return i;
            }
            return 0; // non succederà mai
        }
    }
}

Candy/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Candy.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Candy/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;


namespace Candy.Pages
{
    public class IndexModel : PageModel
    {
        public Prodotto prod = new Prodotto();
        public string action;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
        public void OnPost(int quantProd, string nomeProd, double prezProd, string btn)
        {
            this.prod.quantita = quantProd;
            this.prod.nome = nomeProd;
            this.prod.prezzo = prezProd;
            this.action = btn;
        }
        public void OnPostLogin(string email, string pass)
        {
            if (email == "admin" && pass == "admin")
            {
                Startup.adminRole = true;
            }
        }
        public void OnPostExit(string ciao)
        {
            Startup.adminRole = false;
        }
    }
}

Candy/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Candy.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Candy/Pages/Prodotto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Candy.Pages
{
    public class ProdottoModel : PageModel
    {
        public string idProdotto;
        public int quant;
        public double prez;
        public string imgProdotto;
        public void OnGet(string id)
        {
            this.idProdotto = id;
        }
        public void GetProductData()//ottiene i dati di un determinato prodotto
        {
            for (int i = 0; i < Program.products.Count; i++)
            {
                if (Program.products[i].nome == idProdotto)
                {
                    quant = Program.products[i].quantita;
                    prez = Program.products[i].prezzo;
                    imgProdotto = Program.p.FormatCandy(idProdotto);
                }
            }
        }
        public int GetValue()//serve solo per inizializzare la quantità nella pagina
        {
            if (quant == 0)
                return 0;
            return 1;
        }
    }
}

Candy/Pages/Amministrazione.cshtml
@page
@model Candy.Pages.AmministrazioneModel
@{
}
@{ 
    await Task.Factory.StartNew(() => Program.p.RestockProdotto(@Model.nome, 100, ref Program.products,
            ref Program.modifiedProducts, ref Program.path));
    Model.nome = null;
}
<div class="text-center adm-page">
    <div class="container">
        @for (int i = 0; i < @Program.products.Count; i++)//crea n righe in base a n prodotti
        {
            <div class="row">
                <div class="col-10 offset-1 box-container">

                    <form asp-page="/Amministrazione" method="post">
                        <div class="row element">
                            <div class="col-6 col-sm-4 box-nome">
                                <h6 class="text" id="@Program.products[i].nome">@Program.products[i].nome</h6>
                            </div>
                            <div class="col-6 col-sm-4 box-quantità">
                                <h6 class="text">@Program.products[i].quantita</h6>
                            </div>
                            <input type="hidden" name="nome" value="@Program.products[i].nome" />
                            <button class="col-12 col-sm-4 btn-restock" type="submit">restock</button>
                        </div>
                    </form>
                </div>
            </div>
        }
    </div>
    <span>
        <form asp-page="/Index" asp-page-handler="Exit" class="form-signout" method="post"> <!--logout-->
            <button class="btn btn-primary btn1" type="submit" onclick="Exit">Esci</button>
        </form>
    </span>
</div>

Candy/Pages/Carrello.cshtml
@page
@model CarrelloModel
@{
    ViewData["Title"] = "Carrello";
}
@{
    Program.UpdateList();
    if (@Model.prod.quantita != 0)
    {
        if (@Model.action == "compra")
        {
            await Task.Factory.StartNew(() => CompraItemCarrello(@Model.prod));
        }
        else if (@Model.action == "elimina")
        {
            await Task.Factory.StartNew(() => Program.p.ModificaCarrello(@Model.prod.nome, @Model.prod.quantita,
            @Model.prod.prezzo, ref Startup.carrello, "elimina", Program.products));
        }
        else if (@Model.action == "ricarica")
        {
            await Task.Factory.StartNew(() => Program.p.ModificaCarrello(@Model.prod.nome, @Model.prod.quantita,
            @Model.prod.prezzo, ref Startup.carrello, "ricarica", Program.products));
        }
        else if (@Model.action == "compra-tutto")
        {
            await Task.Factory.StartNew(() => EliminaTutto(ref Startup.carrello));

        }
    }
    Program.UpdateList();
}
<div class="text-center">
    <div class="row carrello-list">
        <div class="col-8 col-md-9">
            @for (int i = 0; i < @Startup.carrello.Count; i++)
            {
                string margin = null;
                if (i != 0)
                {
                    margin = "row-below-first";
                }
                <div class="row @margin">
                    <div class="col-10 offset-1">
                        <div class="row list-item">
                            <div class="col-sm-6 col-md-4 col-xxl-3">
                                <img class="img-fluid img-cart-prod"
                                src="~/images/@Program.p.FormatCandy(Startup.carrello[i].nome)" />
                            </div>
                            <div class="col-sm-5 col-md-6 col-xxl-2">
                                <h3 class="text-prod-list title-text-cart text-nowrap">@Startup.carrello[i].nome</h3>
                            </div>
                            <div class="col-12 col-xxl-7">
                                <form asp-page="/Carrello" method="post" id="cartForm">
                                    <div class="row">
                                        <div class="col-sm-5 offset-sm-1 offset-md-0 col-lg-3 col-xxl-4 btn-quantita">
                                            <button class="btn btn-primary btn-meno btn-prodotto btn-pageCart shadow-none"
                                            type="button submit" name="btn" value="ricarica"
                                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                <img class="img-fluid" src="~/images/meno.png" />
                                            </button>
                                            <input class="quantity carrello-list-quant" min="1"
                                            max="@Program.products[@Model.FindProd(Startup.carrello[i].nome, Program.products)].quantita"
                                            name="quantProd" value="@Startup.carrello[i].quantita" type="number">
                                            <button class="btn btn-primary btn-piu btn-prodotto btn-pageCart shadow-none"
                                            type="button submit" name="btn" value="ricarica"
                                            onclick="this.parentNode.querySelector('input[type=number]').stepUp();">
                                                <img class="img-fluid" src="~/images/piu.png" />
                                            </button>
                                            <input type="hidden" name="nomeProd" value="@Startup.carrello[i].nome" />
                                            <input type="hidden" name="prezProd" value="@Startup.carrello[i].prezzo" />
                                        </div>
                                        <div class="col-sm-2 offset-sm-1 offset-md-0">
                                            <h3 class="text-prod-list price-text-cart">
                                                @CalcolaPrezzo(Startup.carrello[i].prezzo,
                                            Startup.carrello[i].quantita)€</h3>
                                        </div>
                                        <div
                                        class="d-flex col-sm-5 offset-sm-1 offset-md-0 col-md-3 offset-lg-2 offset-xxl-0 col-xxl-3 justify-content-end">
                                            <button class="btn btn-primary btn-compra btn-list-carrello shadow-none"
                                            type="submit" name="btn" value="compra">Compra</button>
                                        </div>
                                        <div class="col-sm-2 col-md-1 offset-sm-1 offset-md-0 col-xxl-2">
                                            <div class="col-12">
                                                <button class="rimuovi" type="submit" name="btn" value="elimina">
                                                    <img class="img-fluid img-rimuovi"
                                                    src="~/images/cestino.png" /></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-4 col-md-3">
            <div class="col-11 carrello-tot">
                <div class="row d-flex justify-content-center">
                    <h3>Totale Carrello</h3>
                    <hr class="separator">
                </div>
                <div class="row tot-text d-flex justify-content-center">
                    <div class="col-12 col-sm-6 col-xxl-3">
                        <h3>Totale:</h3>
                    </div>
                    <div class="col-12 col-sm-5 col-xxl-3">
                        <h3>@CalcolaTotale(@Startup.carrello)€</h3>
                    </div>
                </div>
                <button class="btn btn-primary btn-compra btn-list-carrello-all shadow-none" type="submit" name="btn"
                    value="compra-tutto" form="cartForm">Compra</button>
            </div>
        </div>
    </div>
</div>
@{
    string CalcolaPrezzo(double prezzo, int quantita)// arrotonda il valore a 2 cifre dopo la virgola
    {
        return Math.Round((prezzo * quantita), 2).ToString("N2");
    }
    string CalcolaTotale(List<Prodotto> cart)// calcola il prezzo totale del carrello
    {
        double tot = 0;
        for (int i = 0; i < cart.Count; i++)
            tot += Math.Round((cart[i].prezzo * cart[i].quantita), 2);
        return tot.ToString("N2");
    }
    void CompraItemCarrello(Prodotto itemProd)
    {
        Program.p.TogliProdotto(itemProd.nome, itemProd.quantita, ref Program.products,
        ref Program.modifiedProducts, ref Program.path);
        Program.p.ModificaCarrello(itemProd.nome, itemProd.quantita,
        itemProd.prezzo, ref Startup.carrello, "elimina", Program.products);
    }
    void EliminaTutto(ref List<Prodotto> cart)
    {
        do
        {
            CompraItemCarrello(cart[0]);
        } while (cart.Count != 0);
    }
}

Candy/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@{
    Program.UpdateList();
    if (@Model.prod.quantita != 0)
    {
        if (@Model.action == "compra")
        {
            await Task.Factory.StartNew(() => Program.p.TogliProdotto(@Model.prod.nome, @Model.prod.quantita, ref Program.products,
            ref Program.modifiedProducts, ref Program.path));
        }
        else if (@Model.action == "carrello")
        {
            await Task.Factory.StartNew(() => Program.p.ModificaCarrello(@Model.prod.nome, @Model.prod.quantita,
            @Model.prod.prezzo, ref Startup.carrello, "aggiungi", Program.products));
        }
    }
    Program.UpdateList();
}
<div class="text-center">
    <div class="row">
        <div class="carousel slide container-fluid" id="candyCarousel" data-bs-ride="carousel">
            <ol class="carousel-indicators">
                <li type="button" data-bs-target="#candyCarousel" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></li>
                <li type="button" data-bs-target="#candyCarousel" data-bs-slide-to="1" aria-label="Slide 2">
                </li>
                <li type="button" data-bs-target="#candyCarousel" data-bs-slide-to="2" aria-label="Slide 3">
                </li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="row container-slide">
                        <div class="col-8 order-1 justify-content-center offset-2 order-lg-0 col-lg-4 offset-lg-1">
                            <p class="slide-text">
                                Prova la nuova spedizione veloce in tutta Italia!
                            </p>
                        </div>
                        <div class="col-12 order-0 order-lg-1 col-lg-6 offset-lg-1">
                            <img src="/images/slide_camion.png" class="carousel-img">
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row container-slide">
                        <div class="col-8 order-1 justify-content-center offset-2 order-lg-0 col-lg-4 offset-lg-1">
                            <p class="slide-text">
                                Prova i nuovi arrivati, fidati che non te ne pentirai :b
                            </p>
                        </div>
                        <div class="col-12 order-0 order-lg-1 col-lg-6 offset-lg-1">
                            <img src="/images/slide2.png" class="carousel-img slide2">
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="row container-slide">
                        <div class="col-8 order-1 justify-content-center offset-2 order-lg-0 col-lg-4 offset-lg-1">
                            <p class="slide-text">
                                In arrivo anche golosi sconti su tutta la collezione!
                            </p>
                        </div>
                        <div class="col-12 order-0 order-lg-1 col-lg-6 offset-lg-1">
                            <img src="/images/slide_discount.png" class="carousel-img">
                        </div>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#candyCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#candyCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden"></span>
            </button>
        </div>
    </div>
    <div class="row">
        <h1 class="products-title">La nostra collezione </h1>
    </div>
    <div class="row">
        @{
            for (int i = 0; i < Program.products.Count; i++)
            {
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="box">
                        <a asp-page="/Prodotto" asp-route-ID=@Program.products[i].nome>
                            <div class="img-box">
                                <img class="img-fluid candy-img"
                            src="~/images/@Program.p.FormatCandy(Program.products[i].nome)" />
                            </div>
                            <div class="row detail-box">
                                @{
                                    if (@Program.products[i].quantita > 0)
                                    {
                                        <div class="col-12 text-center">
                                            <h5 class="detail-text">@Program.products[i].nome</h5>
                                        </div>
                                        <div class="col-12 text-center">
                                            <h5 class="detail-text">Prezzo: @Program.products[i].prezzo€</h5>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col-12 text-center">
                                            <h5 class="detail-text">@Program.products[i].nome</h5>
                                        </div>
                                        <div class="col-12 text-center">
                                            <h5 class="detail-text" style="color: red;">Esaurito</h5>
                                        </div>
                                    }
                                }
                            </div>
                        </a>
                    </div>
                </div>
            }
        }
    </div>
</div>

Candy/Pages/Prodotto.cshtml
@page
@model Candy.Pages.ProdottoModel
@{
    ViewData["Title"] = "Pagina Prodotto";
}
@* su @page -> "{id}" per vsualizzare sul link l'id del parametro, questo inoltre sarà necessario per visualizzare la
    pagina*@
@{
    Program.UpdateList(); Model.GetProductData();
}
<div class="text-center">
    <div class="row">
        <div class="col-12 col-lg-6">
            <img class="img-fluid img-prodotto" src="~/images/@Model.imgProdotto" />
        </div>
        <div class="col-12 col-lg-6 info-prodotto">
            <div class="row d-flex justify-content-center">
                <h1 class="nome-prodotto">@Model.idProdotto</h1>
            </div>
            <div class="row justify-content-start disp-prodotto">
                <h5 class="disp-text-prodotto">Disponibilità: @Model.quant</h5>
            </div>
            <form asp-page="/Index" method="post">
                <div class="row sez-quant">
                    <div class="col-3 offset-2 offset-md-3">
                        <h5 class="quant-text-prodotto">Quantità:</h5>
                    </div>
                    <div class="col-7 col-sm-4 text-start">
                        <button class="btn btn-primary btn-meno btn-prodotto" type="button"
                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                            <img class="img-fluid" src="~/images/meno.png" />
                        </button>
                        <input class="quantity" min="0" max="@Model.quant" name="quantProd" value="@Model.GetValue()"
                            type="number">
                        <input type="hidden" name="nomeProd" value="@Model.idProdotto" />
                        <input type="hidden" name="prezProd" value="@Model.prez" />
                        <button class="btn btn-primary btn-piu btn-prodotto" type="button"
                            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                            <img class="img-fluid" src="~/images/piu.png" />
                        </button>
                    </div>
                </div>
                <div class="row sez-acquisto">
                    <div
                        class="d-flex col-3 col-sm-2 offset-1 offset-sm-2 offset-md-3 offset-xl-2 offset-xxl-3 justify-content-center">
                        <h3 class="prezzo-text">@Model.prez €</h3>
                    </div>
                    <div class=" d-flex col-4 col-xxl-3 justify-content-end">
                        <button class="btn btn-primary btn-compra btn-prodotto" type="submit" name="btn"
                            value="compra">Compra</button>
                    </div>
                    <div class=" d-flex col-3 col-xxl-2 justify-content-between">
                        <button class="btn btn-primary btn-carrello btn-prodotto" type="submit" name="btn"
                            value="carrello">
                            <img class="img-fluid" src="~/images/shop_cart_icon.png" />
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Candy/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icona del sito-->
    <link rel="icon" type="image/x-icon" sizes="64x64" href="/favicon.ico">
    <!-- importa il file CSS-->
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/index.css" />
    <link rel="stylesheet" href="~/css/prodotto.css" />
    <link rel="stylesheet" href="~/css/accesso.css" />
    <link rel="stylesheet" href="~/css/carrello.css" />
    <link rel="stylesheet" href="~/css/amministrazione.css" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->

    <title>@ViewData["Title"] - Candy</title>
</head>

<body class="body">
    <header>
        <nav class="navbar navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container-fluid navcandy">
                <a class="navbar-brand" asp-page="/Index">
                    <img class="logoimg" src="~/images/logo_CANDY_MARKET.png" />
                </a>
                <div class="flex-row-reverse">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="img-fluid navbar-brand" asp-page="/Carrello">
                                <img class="shopcartimg" src="~/images/shop_cart_icon.png" />
                            </a>
                        </li>
                        <li class="nav-item">
                            @if (Startup.adminRole)//controlla se l'utente ha fatto l'accesso
                            {
                                <a class="img-fluid navbar-brand" asp-page="/Amministrazione">
                                    <img class="adminimg" src="~/images/admin_icon.png" />
                                </a>
                            }
                            else
                            {
                                <a class="img-fluid navbar-brand" asp-page="/Accesso">
                                    <img class="adminimg" src="~/images/admin_icon.png" />
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid d-block">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
<footer class="footer">
    <div class="row">
        <div class="col-1 offset-1">
            <div class="risorse">
                <h1 class="ris-bold" href="#">Risorse Utili:</h1>
                <a href="#">Recensioni</a> <br><a href="#">Blog</a><br><a href="#">FAQ</a><br><a href="#">Spedizioni</a>
            </div>
        </div>
        <div class="col-4 offset-2">
            <h1 class="footer-title"> Candy Market | Via Roma - 45 100 Rovigo (RO) ITALIA <br> </h1>
            <a class="trans-color-text" href="#">info@candymarket.it</a> | <span itemprop="telephone"><a href="#">+39 123 45 67890</a></span>
            <br><a target="_blank" href="#"> privacy</a> | <a target="_blank" href="#"> cookie policy</a>

            <div class="social-cont">
                <ul class="social-list">
                    <li class="instagram-img">
                        <a target="_blank" href="https://www.instagram.com/haribobr/?hl=it">
                            <img class="instagram-img"
                                src="/images/social/instagram_logo.png" title="Instagram">
                        </a>
                    </li>
                    <li class="twitter-img">
                        <a target="_blank" href="https://twitter.com/haribobrasil">
                            <img class="twitter-img"
                                src="/images/social/twitter_logo.png" title="Twitter">
                        </a>
                    </li>
                    <li class="facebook-img">
                        <a target="_blank" href="https://www.facebook.com/HariboBrasil/">
                            <img class="facebook-img"
                                src="/images/social/facebook_logo.png" title="Facebook">
                        </a>
                    </li>
                </ul>
                <div class="floatstop"></div>
            </div>
            <a> Designed by </a><br>
            <div class="credits">
                <a target="_blank" href="#"><img width="120" src="/images/logo_CANDY_MARKET.png" title="#" alt="#"></a>
            </div>
        </div>
        <div class="col-3 offset-0 prova">
            <div class="shipping">
                <a target="_blank" href="#">
                    <img width="200" src="/images/24 shipping.png" class="shipping-img"
                         align="right">
                </a>
            </div>
        </div>

    </div>
    </footer>

</html>

Candy/Pages/accesso.cshtml
@page
@model AccessoModel
@{
    ViewData["Title"] = "Log In";
}
<div class="text-center">
    <div class="row">
        <div class="col-12 col-sm-8 offset-sm-2 col-md-8 offset-md-2 col-lg-6 offset-lg-3 col-xl-6 offset-lg-3 container">
            <div class="access-container">
                <form asp-page="/Index" asp-page-handler="login" class="form-signin" method="post">
                    <img class="mb-4 img-profile" src="~/images/admin_icon.png">
                    <input type="text" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus value="">
                    <input type="password" id="inputPassword" name="pass" class="form-control" placeholder="Password" required value="">
                    <button class="btn btn-lg btn-primary btn-block btn-accesso shadow-none" type="submit">Accedi</button>
                </form>               
            </div>
        </div>
    </div>
</div>